FROM rust:1.82

RUN cargo install diesel_cli --no-default-features --features postgres --version 2.1.0

WORKDIR /app

COPY ./api/diesel.toml .
COPY ./api/migrations/ /migrations

CMD ["diesel", "migration", "run"]