FROM rust:1.82

# Install SQLite and diesel CLI
RUN apt-get update && apt-get install -y \
    sqlite3 \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

# Install diesel CLI
RUN cargo install diesel_cli --no-default-features --features postgres --version 2.1.0

WORKDIR /app

# Copy diesel configuration
COPY ./api/diesel.toml .
COPY ./api/migrations/ /migrations

CMD ["diesel", "migration", "run"]